### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by HugoGaquere** [LoSealL/openvino2onnx#4]
#### Description
I have converted this onnx model: [yolox_s](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth) to OpenVino IR using OpenVino dev tools.
Now I want to to convert the resulting IR format to onnx using your tool.
But I have the following error:

(openvino) PS C:\DEV\onnx_quant> openvino2onnx yolox_s_ir/yolox_s.xml --model-bin yolox_s_ir/yolox_s.bin
C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\site-packages\openvino2onnx\legalize\compose.py:26: UserWarning: <class 'openvino2onnx.legalize.single_node.Interpolate'> throws an exception
  warnings.warn(f"{type(fn)} throws an exception")
Traceback (most recent call last):
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\Scripts\openvino2onnx.exe\__main__.py", line 7, in <module>
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\site-packages\openvino2onnx\cli\main_cli.py", line 47, in main
    graph = legalize(graph)
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\site-packages\openvino2onnx\legalize\compose.py", line 24, in __call__
    fn(graph)
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\site-packages\openvino2onnx\legalize\mutator.py", line 28, in __call__
    self.trans(graph, i)
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\site-packages\openvino2onnx\legalize\single_node.py", line 220, in trans
    scales_or_size = get_node_on_edge(graph, node, "1")
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\lib\site-packages\openvino2onnx\legalize\utils.py", line 20, in get_node_on_edge
    raise RuntimeError(f"No node on {graph.nodes[node]['name']}:{port}")
RuntimeError: No node on Resize_187:1

#### To Reproduce
Download Yolox S model: [yolox_s](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth)
Convert it using OpenVino dev tool: `mo --input_model yolox_s.onnx`
Convert it back to onnx: `openvino2onnx yolox_s.xml --model-bin yolox_s.bin`

**Comment by LoSealL** [comment]
@HugoGaquere Thanks, reproduced, now looking into the root cause.

**Comment by LoSealL** [comment]
@HugoGaquere issue is resolved, please check the latest commit.
