### ISSUE TITLE
Exception when converting from an optimized IR

### ISSUE THREAD

**Issue by HugoGaquere** [LoSealL/openvino2onnx#6]
#### Description
I have converted this onnx model: [yolox_s](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth) to OpenVino IR using OpenVino dev tools.
Then I ran INT8 calibration with OpenVino Workbench.
Now I want to to convert the resulting IR format to onnx using your tool.
But I have the following error:

Traceback (most recent call last):
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\envs\openvino\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\envs\openvino\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\envs\openvino\Scripts\openvino2onnx.exe\__main__.py", line 7, in <module>
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\envs\openvino\lib\site-packages\openvino2onnx\cli\main_cli.py", line 46, in main
    graph = ir_to_graph(model_url, args.model_bin)
  File "C:\Users\Hugo.Gaquere\AppData\Local\anaconda3\envs\openvino\lib\site-packages\openvino2onnx\ir11.py", line 127, in ir_to_graph
    graph = nx.MultiDiGraph(name=name, **graph_info)
TypeError: networkx.classes.multidigraph.MultiDiGraph() got multiple values for keyword argument 'name'

#### To Reproduce

1. Download Yolox S model: [yolox_s](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth)
2. Convert it using OpenVino dev tool: `mo --input_model yolox_s.onnx`
3. Run INT8 calibration using OpenVino Workbench: 
 -> here the resulting files [yolox_ir.zip](https://github.com/LoSealL/openvino2onnx/files/12226800/yolox_ir.zip)
4. Then convert it back to onnx: `openvino2onnx yolox_s.xml --model-bin yolox_s.bin`

**Comment by LoSealL** [comment]
Hi @HugoGaquere 
On the first hand, this is because a duplicated "name" tag in `rt_info`, which is easy to overcome.
On the other hand, converting quantized model from openvino to onnx is not supported for now, nor in my current roadmap.

I shall improve the error message to point out the exact missing places.

Hoping to hear your responces.

**Comment by LoSealL** [comment]
Solved by the latest commit #10 #11
